ACE-196: Añadir lenguajes
ace-software-dev/Landing pull request #11
Opened 2023-12-12 16:10 UTC by pau-cardoso

## Cómo correr
1. Asegurarse de tener una versión de node superior a la 18.0.0. Se pueden apoyar con la librería nvm
2. Instalar las dependencias en la terminal con `npm i`
3. Correr el servidor localmente con el comando `npm run dev`

## Resultado esperado
Al ejecutar y entrar a localhost automáticamente se visualizará la página en el idioma preferido del usuario. En caso de que el preferido sea español la ruta será plana (`localhost:300/`). Y en caso de que sea inglés o se quiera ir a la versión en inglés la ruta se verá como `localhost:3000/en`.

2023-12-13 16:40 UTC, JR-espacial requested changes
todo bien solo tengop un comentario para tsconfig.json

2023-12-13 16:40 UTC, JR-espacial commented on tsconfig.json
Esta línea actualizada amplía la gama de archivos incluidos en la compilación de TypeScript:
**/**/*.ts y **/**/*.tsx: Este patrón es similar a **/*.ts y **/*.tsx pero podría estar pensado para incluir explícitamente archivos anidados más profundos.

Aunque **/*.ts ya debería cubrir todas las profundidades.
Recomendaría eliminar los otros

2023-12-13 16:53 UTC, JR-espacial commented on tsconfig.json
En mobil no se ve y debe agregarse al hacer la pagina responsiva

2023-12-17 15:02 UTC, pau-cardoso commented on tsconfig.json
Para lo de móvil en estos momentos no lo agregué porque se distorsiona cuando tiene el botón a la derecha. Me esperaré a que se agregué la funcionalidad del hamburguer primero mejor.

2023-12-17 15:31 UTC, JR-espacial approved these changes

2023-12-17 15:36 UTC, merged