Ace 172 por que nosotros
ace-software-dev/Landing pull request #12
Opened 2023-12-13 01:15 UTC by JR-espacial

## Cómo correr
1. Asegurarse de tener una versión de node superior a la 18.0.0. Se pueden apoyar con la librería `nvm`
2. Instalar las dependencias en la terminal con `npm i`
3. Correr el servidor localmente con el comando `npm run dev`

## Resultado esperado
Al ejecutar, debe visualizarse los modelos y el texto de porque nosotros tal cual como en el figma.
Checar estilos, espaciado y legibilidad.

- [ ] Titulo y subtitulo
- [ ] Modelos 3D
- [ ] Textos descriptivos
- [ ] Diseño responsivo para mobil

2023-12-14 02:19 UTC, FelipeYepez requested changes

2023-12-18 04:51 UTC, JR-espacial reviewed
listo

2023-12-28 06:41 UTC, FelipeYepez requested changes
Últimas consideraciones para mantener limpio repositorio

2023-12-28 06:41 UTC, FelipeYepez commented on public/images/chica-ace.png
Archivo ya no es necesario, mejor borrar.

2023-12-28 06:41 UTC, FelipeYepez commented on public/images/ui-ux.png
Archivo ya no es necesario, mejor borrar.

2023-12-28 06:41 UTC, FelipeYepez commented on components/nosotros.tsx
> +                        {/* <img  className="object-scale-down object-center" src="\images\chica-ace.png" alt="chica-ace" /> */}
Eliminar comentario

2023-12-28 06:41 UTC, FelipeYepez commented on components/nosotros.tsx
> +import Spline from "@splinetool/react-spline"
Eliminar import de Spline

2023-12-28 06:41 UTC, FelipeYepez commented on components/nosotros.tsx
> +import Spline from "@splinetool/react-spline"
Igualmente eliminar dependencias de Spline en package.json

2023-12-28 19:37 UTC, merged